### PR TITLE
Cleanup based on Kotlin Conventions

### PR DESCRIPTION
**Pull request by amitdash291**
This PR includes the following:
- Wrap functions in objects for better structure
- Rename the functions to adhere to Kotlin naming conventions
- Make function names more meaningful for readability

### CODE REVIEW

**Comment by amitdash291** [comment]
@daviddenton please review the changes in this PR, eager to get feedback on the cleanup.

**Comment by daviddenton** [comment]
Thanks vm for the contribution. We're not going to merge it, but since you went to so much effort, I'd like to take a bit of time to explain why. Consider this the start of a conversation, happy to elaborate further... :)

The http4k-by-example app is very much written in the "House style" of the http4k team, which definitely does divert from the standard Kotlin idioms, but is one that we have settled on after a few years (and several hundred microservices) being written using the lib. This style is also the one we use on the actual http4k APIs, and one that we recommend to others to adopt to maximise codebase cleanliness and developer productivity.

One element of this style that people often find unusual is the usage of named `object` with `invoke()` methods or functions with `CapitalNames()`. Consider the following example:

```
class MyFilterClass(private val field: String) : Filter {
	...
}
```
vs
```
object MyFilterObject {
	operator fun invoke(field: String) : Filter = ...
}
vs
```
fun MyFilterFunction(field: String) : Filter = ...
}
```
All 3 versions create the same API, and hence we are able to switch at will betwen them without breaking client code. However, by using `MyFilterObject` or `MyFilterFunction`, we can avoid creating a lot of classes which may not actually have any identity or state - as far as the IDE is concerned there is only one type here `Filter` and thus extracting variables, fields or arguments will result in the extracted type being `Filter`, whereas with the first version, `MyFilterClass` will be used.

Choosing between `MyFilterObject` and `MyFilterFunction` is a style choice - I generally (and probably inconsistently) use the object version when there are helper functions or fields/constants which can also live inside the definition of `MyFilterObject`.

The application of that general approach lies a bit opposed to the style introduced in this PR. For instance - SecuritySystem IS an HttpHandler function which can be swapped out for any other HttpHandler, so the usage of `getHttpHandler()` masks that. Similarly, ByeBye IS a ContractRoute (which is also an HttpHandler usable when testing).

**Comment by amitdash291** [comment]
@daviddenton thanks for the detailed explanation. Most of what you said makes sense.

A small question though, I thought the object wrappers will help organize the function within the package structure. If we write functions without any such wrapper, how do we organize them in a big codebase with hundreds of other functions in the same package?

**Comment by daviddenton** [comment]
Floating functions are a namespace pollution concern - but since they are floating within a package, they effectively expose the same amount of pollution as using the `object` version. The only difference between the 2 is that using objects you can collect functions and vals into a neatly "moveable" package. For using functions, you need to be mindful to private/internal them within the files that they are used.

**Comment by amitdash291** [comment]
@daviddenton thanks for the detailed review and prompt responses, we can go ahead and close this PR now.

**Pull request closed without merging**
